const { maintenance_asset_type: Type, maintenance_checklist_unit: Unit, maintenance_checklist_item: Item, inventory, sequelize } = require('../models');
const { Op } = require('sequelize');
const clean = v => String(v || '').trim();
const active = v => v !== false;
const unavailable = e => e?.original?.number === 208 || e?.parent?.number === 208;
const error = (res, e) => unavailable(e) ? res.status(503).json({ message: 'Struktur master maintenance belum tersedia. Jalankan migrasi database terlebih dahulu.' }) : (console.error('Maintenance master:', e), res.status(500).json({ message: `Gagal memproses master maintenance: ${e?.original?.message || e.message}` }));
const sameName = (field, name, extra = {}) => ({ ...extra, [Op.and]: sequelize.where(sequelize.fn('LOWER', sequelize.col(field)), name.toLowerCase()) });

exports.listTypes = async (req, res) => { try { const q = clean(req.query.search); const rows = await Type.findAll({ where: q ? { nama_jenis: { [Op.like]: `%${q}%` } } : {}, order: [['nama_jenis', 'ASC']] }); const counts = await inventory.findAll({ attributes: ['id_asset_type', [sequelize.fn('COUNT', sequelize.col('kode_asset')), 'jumlah_aset']], group: ['id_asset_type'], raw: true }); const map = Object.fromEntries(counts.map(x => [x.id_asset_type, Number(x.jumlah_aset)])); res.json(rows.map(x => ({ ...x.toJSON(), jumlah_aset: map[x.id_asset_type] || 0 }))); } catch (e) { return error(res, e); } };
exports.activeTypes = async (_req, res) => { try { res.json(await Type.findAll({ where: { is_active: true }, order: [['nama_jenis', 'ASC']] })); } catch (e) { return error(res, e); } };
async function typeData(body, id) { const nama_jenis = clean(body.nama_jenis); if (!nama_jenis) return { error: 'Nama kategori maintenance wajib diisi' }; const found = await Type.findOne({ where: sameName('nama_jenis', nama_jenis, id ? { id_asset_type: { [Op.ne]: id } } : {}) }); return found ? { error: 'Kategori maintenance sudah terdaftar' } : { nama_jenis }; }
exports.createType = async (req, res) => { try { const data = await typeData(req.body); if (data.error) return res.status(400).json({ message: data.error }); const row = await Type.create({ ...data, is_active: active(req.body.is_active), created_at: sequelize.fn('getdate'), updated_at: sequelize.fn('getdate') }); res.status(201).json({ message: 'Kategori maintenance berhasil ditambahkan', data: row }); } catch (e) { return error(res, e); } };
exports.updateType = async (req, res) => { try { const row = await Type.findByPk(Number(req.params.id)); if (!row) return res.status(404).json({ message: 'Kategori maintenance tidak ditemukan' }); const data = await typeData(req.body, row.id_asset_type); if (data.error) return res.status(400).json({ message: data.error }); await row.update({ ...data, is_active: req.body.is_active === undefined ? row.is_active : active(req.body.is_active), updated_at: sequelize.fn('getdate') }); res.json({ message: 'Kategori diperbarui; aset yang terhubung tetap memakai kategori ini.', data: row }); } catch (e) { return error(res, e); } };
exports.deactivateType = async (req, res) => { try { const row = await Type.findByPk(Number(req.params.id)); if (!row) return res.status(404).json({ message: 'Kategori maintenance tidak ditemukan' }); await row.update({ is_active: false, updated_at: sequelize.fn('getdate') }); res.json({ message: 'Kategori dinonaktifkan. Pemetaan aset dan riwayat tetap tersimpan.' }); } catch (e) { return error(res, e); } };

exports.listUnits = async (req, res) => { try { const where = req.query.id_asset_type ? { id_asset_type: Number(req.query.id_asset_type) } : {}; res.json(await Unit.findAll({ where, include: [{ model: Type, as: 'maintenance_asset_type' }], order: [['id_asset_type', 'ASC'], ['urutan', 'ASC'], ['nama_unit', 'ASC']] })); } catch (e) { return error(res, e); } };
exports.activeUnits = async (req, res) => { try { res.json(await Unit.findAll({ where: { id_asset_type: Number(req.params.typeId), is_active: true }, order: [['urutan', 'ASC'], ['nama_unit', 'ASC']] })); } catch (e) { return error(res, e); } };
async function unitData(body, id) { const id_asset_type = Number(body.id_asset_type), nama_unit = clean(body.nama_unit); if (!id_asset_type || !nama_unit) return { error: 'Kategori maintenance dan nama unit wajib diisi' }; const type = await Type.findByPk(id_asset_type); if (!type || !type.is_active) return { error: 'Kategori maintenance tidak ditemukan atau nonaktif' }; const found = await Unit.findOne({ where: sameName('nama_unit', nama_unit, { id_asset_type, ...(id ? { id_checklist_unit: { [Op.ne]: id } } : {}) }) }); return found ? { error: 'Nama unit sudah terdaftar pada kategori ini' } : { id_asset_type, nama_unit }; }
exports.createUnit = async (req, res) => { try { const data = await unitData(req.body); if (data.error) return res.status(400).json({ message: data.error }); const row = await Unit.create({ ...data, urutan: Number(req.body.urutan) || 0, is_active: active(req.body.is_active), created_at: sequelize.fn('getdate'), updated_at: sequelize.fn('getdate') }); res.status(201).json({ message: 'Unit pemeriksaan berhasil ditambahkan', data: row }); } catch (e) { return error(res, e); } };
exports.updateUnit = async (req, res) => { try { const row = await Unit.findByPk(Number(req.params.id)); if (!row) return res.status(404).json({ message: 'Unit pemeriksaan tidak ditemukan' }); const data = await unitData(req.body, row.id_checklist_unit); if (data.error) return res.status(400).json({ message: data.error }); await row.update({ ...data, urutan: Number(req.body.urutan) || 0, is_active: req.body.is_active === undefined ? row.is_active : active(req.body.is_active), updated_at: sequelize.fn('getdate') }); res.json({ message: 'Unit pemeriksaan berhasil diperbarui', data: row }); } catch (e) { return error(res, e); } };
exports.deactivateUnit = async (req, res) => { try { const row = await Unit.findByPk(Number(req.params.id)); if (!row) return res.status(404).json({ message: 'Unit pemeriksaan tidak ditemukan' }); await row.update({ is_active: false, updated_at: sequelize.fn('getdate') }); res.json({ message: 'Unit dinonaktifkan. Riwayat tiket tetap tersimpan.' }); } catch (e) { return error(res, e); } };

exports.listItems = async (req, res) => { try { const where = {}; if (req.query.id_asset_type) where.id_asset_type = Number(req.query.id_asset_type); if (req.query.id_checklist_unit) where.id_checklist_unit = Number(req.query.id_checklist_unit); res.json(await Item.findAll({ where, include: [{ model: Type, as: 'maintenance_asset_type' }, { model: Unit, as: 'maintenance_checklist_unit' }], order: [['id_asset_type', 'ASC'], ['id_checklist_unit', 'ASC'], ['urutan', 'ASC'], ['id_maintenance_item', 'ASC']] })); } catch (e) { return error(res, e); } };
async function itemData(body) { const id_asset_type = Number(body.id_asset_type), id_checklist_unit = Number(body.id_checklist_unit), uraian_pemeriksaan = clean(body.uraian_pemeriksaan); if (!id_asset_type || !id_checklist_unit || !uraian_pemeriksaan) return { error: 'Kategori maintenance, unit, dan uraian pemeriksaan wajib diisi' }; const unit = await Unit.findByPk(id_checklist_unit); return !unit || !unit.is_active || unit.id_asset_type !== id_asset_type ? { error: 'Unit pemeriksaan tidak valid atau bukan milik kategori yang dipilih' } : { id_asset_type, id_checklist_unit, uraian_pemeriksaan }; }
const itemValues = (data, body, row) => ({ ...data, alat_metode: clean(body.alat_metode) || null, kriteria_hasil: clean(body.kriteria_hasil) || null, urutan: Number(body.urutan) || 0, is_active: body.is_active === undefined && row ? row.is_active : active(body.is_active), updated_at: sequelize.fn('getdate') });
exports.createItem = async (req, res) => { try { const data = await itemData(req.body); if (data.error) return res.status(400).json({ message: data.error }); const row = await Item.create({ ...itemValues(data, req.body), created_at: sequelize.fn('getdate') }); res.status(201).json({ message: 'Uraian pemeriksaan berhasil ditambahkan', data: row }); } catch (e) { return error(res, e); } };
exports.updateItem = async (req, res) => { try { const row = await Item.findByPk(Number(req.params.id)); if (!row) return res.status(404).json({ message: 'Uraian pemeriksaan tidak ditemukan' }); const data = await itemData(req.body); if (data.error) return res.status(400).json({ message: data.error }); await row.update(itemValues(data, req.body, row)); res.json({ message: 'Uraian pemeriksaan berhasil diperbarui', data: row }); } catch (e) { return error(res, e); } };
exports.deactivateItem = async (req, res) => { try { const row = await Item.findByPk(Number(req.params.id)); if (!row) return res.status(404).json({ message: 'Uraian pemeriksaan tidak ditemukan' }); await row.update({ is_active: false, updated_at: sequelize.fn('getdate') }); res.json({ message: 'Uraian dinonaktifkan. Riwayat tiket tetap tersimpan.' }); } catch (e) { return error(res, e); } };
